/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface DataSnapshot {
    id: string;
    name: string;
    description: string;
    filterParams: Record<string, unknown>;
    count: number;
    createdAt: Date;
    updatedAt: Date;
}
