/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Supported model provider endpoints.
 */
export type ModelEndpoint = "complete" | "edit";

export const ModelEndpoint = {
    Complete: "complete",
    Edit: "edit",
} as const;
