/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HumanloopApi } from "@fern-api/humanloop";

export interface ProjectModelConfig {
    id: string;
    projectId?: string;
    displayName: string;
    modelName: string;
    promptTemplate?: string;
    /** The organization hosting the target model. */
    provider: HumanloopApi.ModelProvider;
    /** Which of the providers' endpoints to use. E.g. Complete, Edit. */
    endpoint: HumanloopApi.ModelEndpoint;
    createdAt: string;
    updatedAt: string;
    lastUsed: string;
    experimentId?: string;
}
