/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { HumanloopApi } from "@fern-api/humanloop";
import * as core from "../../../../core";

export const ModelEndpoint: core.serialization.Schema<serializers.ModelEndpoint.Raw, HumanloopApi.ModelEndpoint> =
    core.serialization.enum_(["complete", "edit"]);

export declare namespace ModelEndpoint {
    type Raw = "complete" | "edit";
}
