/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Feedback {
    value: string;
    dataId?: string;
    user?: string;
    createdAt?: string;
    id: string;
}
