/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface FineTuneFormatting {
    separator?: string;
    completionInitialWhitespace?: string;
    stopSequence?: string;
}
