/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HumanloopApi } from "@fern-api/humanloop";

export interface LogsPage {
    records: HumanloopApi.Log[];
    page: number;
    size: number;
    total: number;
}
