/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateDataSnapshotRequest {
    search?: string;
    metadataSearch?: string;
    startDate?: string;
    endDate?: string;
    name: string;
    description?: string;
}
