/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ExportRawLogsRequest {
    projectId: string;
    search?: string;
    metadataSearch?: string;
    startDate?: string;
    endDate?: string;
}
