/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetLogsRequest {
    projectId: string;
    search?: string;
    metadataSearch?: string;
    startDate?: string;
    endDate?: string;
    size?: number;
    page?: number;
}
