/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { HumanloopApi } from "@fern-api/humanloop";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.model.getFineTunedModels.Response.Raw,
    HumanloopApi.FineTunedModelResponse[]
> = core.serialization.list(
    core.serialization.lazyObject(async () => (await import("../../..")).FineTunedModelResponse)
);

export declare namespace Response {
    type Raw = serializers.FineTunedModelResponse.Raw[];
}
