/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class HumanloopApiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, HumanloopApiTimeoutError.prototype);
    }
}
