/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { HumanloopApi } from "@fern-api/humanloop";
import * as core from "../../../../core";

export const UpdateLabelRequest: core.serialization.ObjectSchema<
    serializers.UpdateLabelRequest.Raw,
    HumanloopApi.UpdateLabelRequest
> = core.serialization.object({
    id: core.serialization.string().optional(),
    name: core.serialization.string().optional(),
    displayName: core.serialization.property("display_name", core.serialization.string().optional()),
    description: core.serialization.string().optional(),
});

export declare namespace UpdateLabelRequest {
    interface Raw {
        id?: string | null;
        name?: string | null;
        display_name?: string | null;
        description?: string | null;
    }
}
