/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HumanloopApi } from "@fern-api/humanloop";

/**
 * Data returned in the payload when adding, editing or deleting a label(s)
 */
export interface Label {
    name: string;
    id: string;
    displayName?: string;
    description?: string;
    count?: number;
    object?: string;
    outputId: number;
    output?: HumanloopApi.Output;
    createdAt?: string;
    updatedAt?: string;
}
