/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HumanloopApi } from "@fern-api/humanloop";

export interface Output {
    id?: number;
    name: string;
    displayName?: string;
    description?: string;
    taskType: HumanloopApi.TaskType;
    dataKey?: string;
    dataType?: HumanloopApi.DataType;
    projectId?: number;
    object?: string;
}
