/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * What ML tasks we support for our outputs
 */
export type TaskType =
    | "classification"
    | "multi_label_classification"
    | "sequence_tagging"
    | "ordinal_regression"
    | "generation";

export const TaskType = {
    Classification: "classification",
    MultiLabelClassification: "multi_label_classification",
    SequenceTagging: "sequence_tagging",
    OrdinalRegression: "ordinal_regression",
    Generation: "generation",
} as const;
