/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The definition of a Label used as part of an output specification for a project and/or learner. The name will be a unique key (within the scope of a single output) that will be referenced by annotations and predictions
 */
export interface UpdateLabelRequest {
    id?: string;
    name?: string;
    displayName?: string;
    description?: string;
}
