/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { HumanloopApi } from "@fern-api/humanloop";
import * as core from "../../../../core";

export const ModelProvider: core.serialization.Schema<serializers.ModelProvider.Raw, HumanloopApi.ModelProvider> =
    core.serialization.enum_(["openai", "ai21", "mock", "anthropic"]);

export declare namespace ModelProvider {
    type Raw = "openai" | "ai21" | "mock" | "anthropic";
}
