/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetAnnotationsRequest {
    projectId: number;
    size?: number;
    page?: number;
    complete?: boolean;
    flagged?: boolean;
    reviewed?: boolean;
    user?: string;
    keywords?: string;
    taskId?: number;
}
