/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UpdateAnnotationRequest {
    reviewed?: boolean;
    start?: number;
    end?: number;
    labelId?: string;
    strength?: number;
    text?: string;
}
