/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { HumanloopApi } from "@fern-api/humanloop";
import * as core from "../../../../core";

export const Request: core.serialization.Schema<
    serializers.annotation.create.Request.Raw,
    HumanloopApi.CreateAnnotationRequest
> = core.serialization.object({
    taskId: core.serialization.property("task_id", core.serialization.number()),
    externalId: core.serialization.property("external_id", core.serialization.string().optional()),
    labelId: core.serialization.property("label_id", core.serialization.string().optional()),
    start: core.serialization.number().optional(),
    end: core.serialization.number().optional(),
    text: core.serialization.string().optional(),
    strength: core.serialization.number().optional(),
});

export declare namespace Request {
    interface Raw {
        task_id: number;
        external_id?: string | null;
        label_id?: string | null;
        start?: number | null;
        end?: number | null;
        text?: string | null;
        strength?: number | null;
    }
}
