/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { HumanloopApi } from "@fern-api/humanloop";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.metrics.getMetricsForModelConfigs.Response.Raw,
    HumanloopApi.ModelConfigMetrics[]
> = core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).ModelConfigMetrics));

export declare namespace Response {
    type Raw = serializers.ModelConfigMetrics.Raw[];
}
