/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { HumanloopApi } from "@fern-api/humanloop";
import * as core from "../../../../core";

export const Request: core.serialization.Schema<
    serializers.monitoring.exportFineTuneLogs.Request.Raw,
    HumanloopApi.FineTuneFormatting
> = core.serialization.lazyObject(async () => (await import("../../..")).FineTuneFormatting);

export declare namespace Request {
    type Raw = serializers.FineTuneFormatting.Raw;
}
