/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HumanloopApi } from "@fern-api/humanloop";

export interface FineTuneModelRequest {
    name: string;
    dataSnapshot: string;
    config: HumanloopApi.FineTuneConfig;
    providerApiKeys: HumanloopApi.ProviderApiKeys;
}
