/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { HumanloopApi } from "@fern-api/humanloop";
import * as core from "../../../../core";

export const Feedback: core.serialization.ObjectSchema<serializers.Feedback.Raw, HumanloopApi.Feedback> =
    core.serialization.object({
        value: core.serialization.string(),
        dataId: core.serialization.property("data_id", core.serialization.string().optional()),
        user: core.serialization.string().optional(),
        createdAt: core.serialization.property("created_at", core.serialization.string().optional()),
        id: core.serialization.string(),
    });

export declare namespace Feedback {
    interface Raw {
        value: string;
        data_id?: string | null;
        user?: string | null;
        created_at?: string | null;
        id: string;
    }
}
