/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { HumanloopApi } from "@fern-api/humanloop";
import * as core from "../../../../core";

export const FineTuneFormatting: core.serialization.ObjectSchema<
    serializers.FineTuneFormatting.Raw,
    HumanloopApi.FineTuneFormatting
> = core.serialization.object({
    separator: core.serialization.string().optional(),
    completionInitialWhitespace: core.serialization.property(
        "completion_initial_whitespace",
        core.serialization.string().optional()
    ),
    stopSequence: core.serialization.property("stop_sequence", core.serialization.string().optional()),
});

export declare namespace FineTuneFormatting {
    interface Raw {
        separator?: string | null;
        completion_initial_whitespace?: string | null;
        stop_sequence?: string | null;
    }
}
