/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { HumanloopApi } from "@fern-api/humanloop";
import * as core from "../../../../core";

export const LogDataSnapshot: core.serialization.ObjectSchema<
    serializers.LogDataSnapshot.Raw,
    HumanloopApi.LogDataSnapshot
> = core.serialization.object({
    id: core.serialization.string(),
    name: core.serialization.string(),
    count: core.serialization.number(),
});

export declare namespace LogDataSnapshot {
    interface Raw {
        id: string;
        name: string;
        count: number;
    }
}
