/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { HumanloopApi } from "@fern-api/humanloop";
import * as core from "../../../../core";

export const LogsPage: core.serialization.ObjectSchema<serializers.LogsPage.Raw, HumanloopApi.LogsPage> =
    core.serialization.object({
        records: core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).Log)),
        page: core.serialization.number(),
        size: core.serialization.number(),
        total: core.serialization.number(),
    });

export declare namespace LogsPage {
    interface Raw {
        records: serializers.Log.Raw[];
        page: number;
        size: number;
        total: number;
    }
}
