/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HumanloopApi } from "@fern-api/humanloop";

export interface FineTunedModelResponse {
    id: string;
    name: string;
    status: string;
    modelName?: string;
    /** Details of the corresponding immutable dataset used for fine-tuning. */
    dataSnapshot: HumanloopApi.DataSnapshot;
    providerId?: string;
    /** Configuration details for the fine-tuned model. */
    config: HumanloopApi.FineTuneConfig;
    createdAt: string;
    updatedAt: string;
}
