/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HumanloopApi } from "@fern-api/humanloop";

export interface FineTuneConfig {
    /** The company who is hosting the target model.This is used only if an existing experiment_id or model_config_id are not provided. */
    provider?: HumanloopApi.ModelProvider;
    baseModel: string;
    validationSplit?: number;
    useCorrections?: boolean;
    promptTemplate?: string;
    generationTemplate?: string;
}
