/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Supported model providers.
 */
export type ModelProvider = "openai" | "ai21" | "mock" | "anthropic";

export const ModelProvider = {
    Openai: "openai",
    Ai21: "ai21",
    Mock: "mock",
    Anthropic: "anthropic",
} as const;
