/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HumanloopApi } from "@fern-api/humanloop";

export interface UpdateFineTunedModelsResponse {
    updated: HumanloopApi.UpdateFineTunedModelResponse[];
    failed: HumanloopApi.UpdateFineTunedModelResponse[];
}
