/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { HumanloopApi } from "@fern-api/humanloop";
import * as core from "../../../../core";

export const AnnotationUserResponse: core.serialization.ObjectSchema<
    serializers.AnnotationUserResponse.Raw,
    HumanloopApi.AnnotationUserResponse
> = core.serialization.object({
    id: core.serialization.number(),
    username: core.serialization.string(),
    fullName: core.serialization.property("full_name", core.serialization.string().optional()),
    emailAddress: core.serialization.property("email_address", core.serialization.string()),
});

export declare namespace AnnotationUserResponse {
    interface Raw {
        id: number;
        username: string;
        full_name?: string | null;
        email_address: string;
    }
}
