/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { HumanloopApi } from "@fern-api/humanloop";
import * as core from "../../../../core";

export const DataSnapshot: core.serialization.ObjectSchema<serializers.DataSnapshot.Raw, HumanloopApi.DataSnapshot> =
    core.serialization.object({
        id: core.serialization.string(),
        name: core.serialization.string(),
        description: core.serialization.string(),
        filterParams: core.serialization.property(
            "filter_params",
            core.serialization.record(core.serialization.string(), core.serialization.unknown())
        ),
        count: core.serialization.number(),
        createdAt: core.serialization.property("created_at", core.serialization.date()),
        updatedAt: core.serialization.property("updated_at", core.serialization.date()),
    });

export declare namespace DataSnapshot {
    interface Raw {
        id: string;
        name: string;
        description: string;
        filter_params: Record<string, unknown>;
        count: number;
        created_at: string;
        updated_at: string;
    }
}
