/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HumanloopApi } from "@fern-api/humanloop";

/**
 * An instance of a user-provided annotation
 */
export interface Annotation {
    id: string;
    externalId: string;
    confidence?: number;
    user: HumanloopApi.AnnotationUserResponse;
    task: HumanloopApi.AnnotationTaskResponse;
    start?: number;
    end?: number;
    text?: string;
    strength?: number;
    labelId: string;
    label: HumanloopApi.Label;
    resultType: string;
    reviewed?: boolean;
}
