/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An instance of the user who made an annotation
 */
export interface AnnotationUserResponse {
    id: number;
    username: string;
    fullName?: string;
    emailAddress: string;
}
