/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An instance of a task the annotation was created for
 */
export interface AnnotationTaskResponse {
    id: number;
    url?: string;
}
