/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type DataType =
    | "text"
    | "categorical"
    | "multi_categorical"
    | "quantitative"
    | "character_offsets"
    | "url"
    | "ordinal_regression"
    | "file_pdf";

export const DataType = {
    Text: "text",
    Categorical: "categorical",
    MultiCategorical: "multi_categorical",
    Quantitative: "quantitative",
    CharacterOffsets: "character_offsets",
    Url: "url",
    OrdinalRegression: "ordinal_regression",
    FilePdf: "file_pdf",
} as const;
