/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const HumanloopApiEnvironment = {
    Production: "https://api.humanloop.com/v2",
} as const;

export type HumanloopApiEnvironment = typeof HumanloopApiEnvironment.Production;
