/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { HumanloopApi } from "@fern-api/humanloop";
import * as core from "../../../../core";

export const Request: core.serialization.Schema<
    serializers.dataSnapshot.create.Request.Raw,
    Omit<HumanloopApi.CreateDataSnapshotRequest, "search" | "metadataSearch" | "startDate" | "endDate">
> = core.serialization.object({
    name: core.serialization.string(),
    description: core.serialization.string().optional(),
});

export declare namespace Request {
    interface Raw {
        name: string;
        description?: string | null;
    }
}
