/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { HumanloopApi } from "@fern-api/humanloop";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.dataSnapshot.getAll.Response.Raw,
    HumanloopApi.DataSnapshot[]
> = core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).DataSnapshot));

export declare namespace Response {
    type Raw = serializers.DataSnapshot.Raw[];
}
