/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { HumanloopApi } from "@fern-api/humanloop";
import * as core from "../../../../core";

export const Request: core.serialization.Schema<
    serializers.dataSnapshot.update.Request.Raw,
    HumanloopApi.UpdateDataSnapshotRequest
> = core.serialization.object({
    name: core.serialization.string().optional(),
    description: core.serialization.string().optional(),
});

export declare namespace Request {
    interface Raw {
        name?: string | null;
        description?: string | null;
    }
}

export const Response: core.serialization.Schema<
    serializers.dataSnapshot.update.Response.Raw,
    HumanloopApi.DataSnapshot
> = core.serialization.lazyObject(async () => (await import("../../..")).DataSnapshot);

export declare namespace Response {
    type Raw = serializers.DataSnapshot.Raw;
}
